# This is a basic workflow to help you get started with Actions

name: CI_MLRean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo CI - MLReanimacao 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Projeto 1 da disciplina de Aprendizagem de Máquina - PPgEEC/UFRN
          echo Machine Learning em Reanimação Neonatal
          
      - name:  Setup Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
        
      - name:  Wandb login
        run: wandb login ${{ secrets.WANDB_KEY_ID }}
        
      - name: API testing
        run: pytest api/mlrean_api -vv -s
